name: 🐛 Bug
description: File a bug/issue
labels: [🐛 Bug, Needs Triage]
body:
- type: textarea
  attributes:
    label: Description
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. In this environment...
      2. With this config...
      3. Run '...'
      4. See error...
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: Windows 11
        - **Version**: 1.0.0
        - **Framework**: .NET 4.8
    value: |
        - OS:
        - Version:
        - Framework:
    render: markdown
  validations:
    required: false
